version: "3"

services:
    server:
        build: ./back
        #  NO NEED TO EXPOSE BACKEND SERVER OUTSIDE DOCKER
        #        expose:
        #            - ${APP_SERVER_PORT}
        environment:
            PORT: ${APP_SERVER_PORT}
        #  NO NEED TO EXPOSE BACKEND SERVER OUTSIDE DOCKER
        #        ports:
        #            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
            - ./back:/usr/src/app
        command: npm run start

    client:
        build: ./front
        environment:
            - REACT_APP_PORT=${REACT_APP_PORT}
            - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
        expose:
            - ${REACT_APP_PORT}
        ports:
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
            - ./front/src:/usr/src/app/src
            - ./front/public:/usr/src/app/public
        links:
            - server
        command: npm run start
